// Command shagen emits the arm64 hardware-SHA kernel block_arm64.s.
//
// The kernel hashes `lanes` independent 33-byte messages per loop iteration,
// each as a single padded SHA-256 block. Unlike a NEON "lane = message" design,
// the ARMv8 SHA-256 instructions (SHA256H/H2/SU0/SU1) process ONE message at a
// time across the four 32-bit lanes of the state vectors, so multiple messages
// are run as independent register-disjoint streams advanced in lockstep. Each
// SHA256H/H2 group is latency-bound; emitting the same group for every lane
// back-to-back lets the out-of-order core overlap the independent streams and
// hide that latency, which is where the multi-buffer speedup comes from.
//
// Message preprocessing (fixed 33-byte single block, big-endian schedule):
//
//	W[0..7] = message bytes 0..31 (8 big-endian words)
//	W[8]    = msg[32]<<24 | 0x00800000   (last byte + the 0x80 padding bit)
//	W[9..14]= 0
//	W[15]   = 0x108                       (264 = 33*8, the message bit length)
//
// Only bytes 0..32 of each message are read (a 16+16 byte vector load plus a
// single-byte load), never the inter-message stride padding, so the kernel is
// safe at any stride >= 33 and never over-reads the caller's buffer.
//
// Register allocation (K and IV live in rodata, loaded on demand):
//
//	V[m*7+0..3] message schedule words for lane m (recycled by SU0/SU1)
//	V[m*7+4]    lane m working ABCD
//	V[m*7+5]    lane m working EFGH
//	V[m*7+6]    lane m saved ABCD (the pre-update ABCD consumed by SHA256H2)
//	V[7*L]      K scratch (one round group, shared by all lanes)
//	V[7*L+1]    IV scratch (setup and finalize only)
//	V[7*L+2..]  per-lane W+K scratch pool
//
// The generator is the single source of truth for block_arm64.s; do not edit
// the assembly by hand (see CONTRIBUTING.md).
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// modulePath is the import path of the module that owns the generated file. It
// is verified before writing so a wrong working directory fails loudly instead
// of silently writing outside the repo.
const modulePath = "github.com/Asylian21/sha256mb"

// lanes is the number of independent messages interleaved per loop iteration.
// 2 and 4 both fit the 32-register file with K/IV in memory; pick the faster by
// measurement (see PERFORMANCE.md). The backend name in block_arm64.go must
// match (sha2x<lanes>).
const lanes = 4

// k are the 64 SHA-256 round constants.
var k = [64]uint32{
	0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
	0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
	0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
	0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
	0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
	0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
	0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
	0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
}

// iv is the SHA-256 initial hash value (H0..H7).
var iv = [8]uint32{
	0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
	0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
}

// Auxiliary vector registers, placed above the per-lane state.
var (
	regK   = 7*lanes + 0  // K scratch for the current round group
	regIV  = 7*lanes + 1  // IV scratch (setup/finalize only)
	wkPool = wkPoolRegs() // per-lane W+K scratch pool
)

func wkPoolRegs() []int {
	var p []int
	for r := 7*lanes + 2; r <= 31; r++ {
		p = append(p, r)
	}
	if len(p) == 0 {
		panic("shagen: no registers left for the W+K scratch pool")
	}
	return p
}

// laneReg returns the vector register holding the given role of lane m. Roles:
// schedule words 0..3, then "abcd", "efgh", "saved".
func sched(m, w int) int { return m*7 + w }
func abcd(m int) int     { return m*7 + 4 }
func efgh(m int) int     { return m*7 + 5 }
func saved(m int) int    { return m*7 + 6 }
func wk(m int) int       { return wkPool[m%len(wkPool)] }

func main() {
	root := repoRoot()
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("// Code generated by internal/shagen; DO NOT EDIT.")
	p("//go:build arm64")
	p("")
	p("#include \"textflag.h\"")
	p("")
	p("// func hash33SHA2(dst, src []byte, n, stride int)")
	p("//")
	p("// Hashes %d independent 33-byte messages per loop iteration into 32-byte", lanes)
	p("// digests. The caller guarantees n is a positive multiple of %d; the scalar", lanes)
	p("// tail is handled in Go. Only bytes 0..32 of each message are read.")
	p("TEXT ·hash33SHA2(SB), NOSPLIT, $0-64")
	p("\tMOVD\tdst_base+0(FP), R0")
	p("\tMOVD\tsrc_base+24(FP), R1")
	p("\tMOVD\tn+48(FP), R2")
	p("\tMOVD\tstride+56(FP), R5")
	p("\tCBZ\tR2, done")
	p("")
	p("loop:")

	// Per-lane source base pointers: lane 0 is R1, lane m is lane (m-1) + stride.
	p("\t// Per-lane message base pointers (lane m = R1 + m*stride).")
	for m := 1; m < lanes; m++ {
		p("\tADD\tR5, %s, %s", baseReg(m-1), baseReg(m))
	}
	p("")

	// Setup: load each message, build its schedule, seed its state from the IV.
	p("\t// Load the IV (H0..H7) once; it seeds every lane and is re-added at the end.")
	p("\tMOVD\t$\u00b7sha256mbIV(SB), R4")
	p("\tVLD1\t(R4), [V%d.S4]", regIV) // not strictly needed yet; setup reloads per lane
	for m := 0; m < lanes; m++ {
		setupLane(&b, m)
	}
	p("")

	// 16 round groups, each shared K loaded once and applied to every lane in
	// lockstep so the independent SHA256H chains overlap.
	p("\t// 16 round groups; K loaded once per group and shared across lanes.")
	p("\tMOVD\t$\u00b7sha256mbK(SB), R4")
	for g := 0; g < 16; g++ {
		p("\t// --- round group %d ---", g)
		p("\tVLD1.P\t16(R4), [V%d.S4]", regK)
		for m := 0; m < lanes; m++ {
			groupBody(&b, m, g)
		}
	}
	p("")

	// Finalize: add the IV back, byte-swap to big-endian, store 32 bytes/lane.
	p("\t// Finalize: digest = REV32(state + IV); store %d*32 bytes.", lanes)
	p("\tMOVD\t$\u00b7sha256mbIV(SB), R4")
	for m := 0; m < lanes; m++ {
		finalizeLane(&b, m)
	}
	p("")

	// Advance to the next group of lanes and loop.
	p("\t// Advance src to the next lane group and dst already moved via stores.")
	p("\tADD\tR5, %s, R1", baseReg(lanes-1))
	p("\tSUBS\t$%d, R2, R2", lanes)
	p("\tBNE\tloop")
	p("done:")
	p("\tRET")
	p("")

	emitConstants(&b)

	write(filepath.Join(root, "block_arm64.s"), []byte(b.String()))
}

// baseReg returns the general register holding lane m's message base pointer.
func baseReg(m int) string {
	if m == 0 {
		return "R1"
	}
	return fmt.Sprintf("R%d", 5+m) // R6, R7, R8 for lanes 1..3
}

// setupLane emits the message load, schedule construction and state seeding for
// one lane. It reads exactly 33 bytes from the lane's base pointer.
func setupLane(b *strings.Builder, m int) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	base := baseReg(m)
	p("\t// lane %d: load message, build schedule, seed state", m)
	p("\tVLD1\t(%s), [V%d.B16]", base, sched(m, 0)) // bytes 0..15 -> W0..3 (pre-swap)
	p("\tADD\t$16, %s, R3", base)
	p("\tVLD1\t(R3), [V%d.B16]", sched(m, 1)) // bytes 16..31 -> W4..7 (pre-swap)
	p("\tVREV32\tV%d.B16, V%d.B16", sched(m, 0), sched(m, 0))
	p("\tVREV32\tV%d.B16, V%d.B16", sched(m, 1), sched(m, 1))
	// W8 = msg[32]<<24 | 0x00800000.
	p("\tMOVBU\t32(%s), R3", base)
	p("\tLSL\t$24, R3, R3")
	p("\tMOVD\t$0x00800000, R10")
	p("\tORR\tR10, R3, R3")
	p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", sched(m, 2), sched(m, 2), sched(m, 2))
	p("\tVMOV\tR3, V%d.S[0]", sched(m, 2))
	// W12..15 = 0,0,0,0x108.
	p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", sched(m, 3), sched(m, 3), sched(m, 3))
	p("\tMOVD\t$0x108, R3")
	p("\tVMOV\tR3, V%d.S[3]", sched(m, 3))
	// Seed working state from the IV (loaded into regIV at the top of the loop).
	p("\tVMOV\tV%d.B16, V%d.B16", regIV, abcd(m)) // V[regIV] currently holds IV[0..3]
	p("\tMOVD\t$\u00b7sha256mbIV(SB), R3")
	p("\tADD\t$16, R3, R3")
	p("\tVLD1\t(R3), [V%d.S4]", efgh(m)) // IV[4..7]
	p("\tVMOV\tV%d.B16, V%d.B16", abcd(m), saved(m))
}

// groupBody emits one SHA-256 round group (4 rounds) for one lane, mirroring the
// proven crypto/sha256 arm64 sequence: compute W+K, advance the schedule
// (SHA256SU0 for groups 0..11, SHA256SU1 for groups 1..12), then the hash update
// SHA256H/SHA256H2 with the saved pre-update ABCD.
func groupBody(b *strings.Builder, m, g int) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	cur := sched(m, g%4)
	w := wk(m)
	// W+K for this group (read schedule BEFORE the SU0 advances it).
	p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", regK, cur, w)
	if g <= 11 {
		next := sched(m, (g+1)%4)
		p("\tSHA256SU0\tV%d.S4, V%d.S4", next, cur)
	}
	if g >= 1 && g <= 12 {
		u := (g - 1) % 4
		p("\tSHA256SU1\tV%d.S4, V%d.S4, V%d.S4", sched(m, (u+3)%4), sched(m, (u+2)%4), sched(m, u))
	}
	p("\tSHA256H\tV%d.S4, V%d, V%d", w, efgh(m), abcd(m))
	p("\tSHA256H2\tV%d.S4, V%d, V%d", w, saved(m), efgh(m))
	p("\tVMOV\tV%d.B16, V%d.B16", abcd(m), saved(m))
}

// finalizeLane adds the IV back into the lane's state, byte-reverses each word
// to big-endian, and stores the 32-byte digest, advancing R0 by 32.
func finalizeLane(b *strings.Builder, m int) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	p("\t// lane %d: state += IV, byte-swap, store 32 bytes", m)
	p("\tVLD1\t(R4), [V%d.S4]", regIV) // IV[0..3]
	p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", regIV, abcd(m), abcd(m))
	p("\tADD\t$16, R4, R3")
	p("\tVLD1\t(R3), [V%d.S4]", regIV) // IV[4..7]
	p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", regIV, efgh(m), efgh(m))
	p("\tVREV32\tV%d.B16, V%d.B16", abcd(m), abcd(m))
	p("\tVREV32\tV%d.B16, V%d.B16", efgh(m), efgh(m))
	p("\tVST1.P\t[V%d.B16], 16(R0)", abcd(m))
	p("\tVST1.P\t[V%d.B16], 16(R0)", efgh(m))
}

// emitConstants writes the K and IV rodata tables.
func emitConstants(b *strings.Builder) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	p("// SHA-256 round constants K[0..63].")
	for i, v := range k {
		p("DATA\t\u00b7sha256mbK+%#04x(SB)/4, $%#08x", i*4, v)
	}
	p("GLOBL\t\u00b7sha256mbK(SB), RODATA|NOPTR, $256")
	p("")
	p("// SHA-256 initial hash value H0..H7.")
	for i, v := range iv {
		p("DATA\t\u00b7sha256mbIV+%#04x(SB)/4, $%#08x", i*4, v)
	}
	p("GLOBL\t\u00b7sha256mbIV(SB), RODATA|NOPTR, $32")
}

// repoRoot resolves the module root from the generator's working directory
// (go:generate runs "cd internal/shagen && go run .") and verifies it.
func repoRoot() string {
	root := filepath.Dir(filepath.Dir(must(os.Getwd())))
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		panic(fmt.Errorf("shagen: cannot read go.mod at resolved root %q: %w", root, err))
	}
	if !bytes.Contains(data, []byte("module "+modulePath)) {
		panic(fmt.Errorf("shagen: resolved root %q is not module %q", root, modulePath))
	}
	return root
}

func must[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}

func write(path string, b []byte) {
	old, _ := os.ReadFile(path)
	if bytes.Equal(old, b) {
		return
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		panic(fmt.Errorf("write %s: %w", path, err))
	}
}
