package hash160mb

// The arm64 fused NEON and SHA3 kernels are generated by internal/fusedgen,
// which is their single source of truth (see CONTRIBUTING.md). Regenerate with
// `go generate ./...` from the module root after editing the generator.

//go:generate sh -c "cd internal/fusedgen && go run ."
