package hash160mb

// The arm64 fused kernel block_arm64.s is generated by internal/fusedgen, which
// is the single source of truth for it (see CONTRIBUTING.md). Regenerate with
// `go generate ./...` from the module root after editing the generator.

//go:generate sh -c "cd internal/fusedgen && go run ."
